# Generated by Django 2.0.2 on 2018-03-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NM_Demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='CardData',
        ),
    ]
