# Generated by Django 2.0.2 on 2018-03-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM_Demo', '0002_auto_20180301_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='image_url',
            field=models.CharField(default='http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=430593&type=card', max_length=256),
        ),
        migrations.AddField(
            model_name='carddata',
            name='mana_cost',
            field=models.CharField(default='R', max_length=10),
        ),
        migrations.AddField(
            model_name='carddata',
            name='power',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='carddata',
            name='toughness',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='carddata',
            name='type',
            field=models.CharField(default='Instant', max_length=256),
        ),
    ]
