# Generated by Django 2.0.2 on 2018-03-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM_Demo', '0003_auto_20180301_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='carddata',
            name='mana_cost',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
