# Generated by Django 2.0.2 on 2018-03-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM_Demo', '0004_auto_20180301_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='mana_cost',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='power',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='toughness',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='type',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
