# Generated by Django 2.0.2 on 2018-03-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NM_Demo', '0005_auto_20180301_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddata',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='carddata',
            name='mana_cost',
        ),
        migrations.RemoveField(
            model_name='carddata',
            name='power',
        ),
        migrations.RemoveField(
            model_name='carddata',
            name='toughness',
        ),
    ]
