# Generated by Django 2.0.2 on 2018-03-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NM_Demo', '0006_auto_20180301_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardData',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
